import Foundation

enum ChronicleStrings {
    static let title = String(localized: "Chronicle")
    static let emptyTitle = String(localized: "What happened here?")
    static let emptyBody = String(localized: "Capture something worth keeping.")
    static let writePlaceholder = String(localized: "Write a moment…")
    static let add = String(localized: "Add")
    static let remove = String(localized: "Remove")
    static let removeTitle = String(localized: "Remove this moment?")
    static let moveUp = String(localized: "Move up")
    static let moveDown = String(localized: "Move down")
    static let edit = String(localized: "Edit text moment")
    static let cancel = String(localized: "Cancel")
    static let done = String(localized: "Done")
    static let unfinishedMoment = String(localized: "You have an unfinished moment.")
    static let addMoment = String(localized: "Add Moment")
    static let discard = String(localized: "Discard")
    static let saveError = String(localized: "Chronicle could not be saved. Try again.")
    static let gallery = String(localized: "Gallery")
    static let camera = String(localized: "Camera")
    static let video = String(localized: "Video")
    static let photo = String(localized: "Photo")
    static let openMedia = String(localized: "Open media")
    static let closeMedia = String(localized: "Close media")
    static let mediaUnavailable = String(localized: "Media unavailable")
    static let cameraUnavailable = String(localized: "Camera is unavailable on this device.")
    static let cameraPermissionDenied = String(localized: "Camera permission is required to capture media.")
    static let mediaImporting = String(localized: "Adding media…")
    static let voiceNote = String(localized: "Voice note")
    static let play = String(localized: "Play")
    static let pause = String(localized: "Pause")
    static let playbackFailed = String(localized: "This recording could not be played.")
    static let voiceUnavailable = String(localized: "Voice note unavailable")
    static let originalTranscript = String(localized: "Original Transcript")
    static let editedTranscript = String(localized: "Edited Transcript")
    static let dictate = String(localized: "Start dictation")
    static let recordVoice = String(localized: "Start voice recording")
    static let recording = String(localized: "Recording")
    static let finishRecording = String(localized: "Finish recording")
    static let discardRecording = String(localized: "Discard recording")
    static let listening = String(localized: "Listening")
    static let finishDictation = String(localized: "Finish")
    static let speechUnavailable = String(localized: "On-device speech recognition is unavailable.")
    static let microphoneUnavailable = String(localized: "Microphone permission is required to use Mic.")
    static let transcribe = String(localized: "Transcribe")
    static let transcribing = String(localized: "Transcribing…")
    static let transcriptionFailed = String(localized: "Transcription failed.")
    static let transcriptionUnavailable = String(localized: "On-device transcription is unavailable.")
    static let editTranscript = String(localized: "Edit transcript")
    static let retry = String(localized: "Retry")
    static let editMedia = String(localized: "Edit media moment")
    static let editingMedia = String(localized: "Editing media moment")
    static let moveMediaEarlier = String(localized: "Move media earlier")
    static let moveMediaLater = String(localized: "Move media later")
    static let removePhoto = String(localized: "Remove photo")
    static let removeVideo = String(localized: "Remove video")
    static let mediaReorderHint = String(localized: "Swipe through media. Use the arrows to reorder.")
    static let mediaEditCaptureHint = String(
        localized: "Gallery, Camera, and Video add to this moment while you edit."
    )

    static func mediaPosition(_ position: Int, _ count: Int) -> String {
        String(localized: "\(position) of \(count)")
    }

    static func mediaFailed(_ count: Int) -> String {
        String(localized: "\(count) item(s) couldn’t be added.")
    }
}
