import Foundation

enum IdeaGroveStrings {
    static let title = String(localized: "Idea Grove")
    static let alive = String(localized: "Alive")
    static let completed = String(localized: "Completed")
    static let flow = String(localized: "Flow")
    static let markInsight = String(localized: "Mark as Insight")
    static let markCompleted = String(localized: "Mark Completed")
    static let revive = String(localized: "Revive")
    static let deletePulse = String(localized: "Delete Pulse")
    static let deleteBody = String(localized: "This will delete the actual Pulse from Scyra. If this Pulse has Flow history in Idea Grove, the Idea Grove link will be removed, but your saved Flows will remain in Story.")
    static let cancel = String(localized: "Cancel")
    static let untitled = String(localized: "Untitled Pulse")
    static let noFlowsYet = String(localized: "No Flows yet")
    static let noFlowsFromPulse = String(localized: "No Flows from this Pulse yet.")
    static let startFlowHint = String(localized: "Start a Flow to build on this idea.")
    static let flowHistory = String(localized: "Flow history")
    static let insight = String(localized: "Insight")
    static let noPulseFlows = String(localized: "No Pulse Flows yet")
    static let noCompletedPulseFlows = String(localized: "No completed Pulse Flows yet")
    static let completedInsightsSummary = String(localized: "Insights are complete as-is. Completed Idea Flow time will appear here.")
    static let noIdeas = String(localized: "No ideas yet")
    static let createPulseHint = String(localized: "Capture a Pulse when something sparks. It will appear here in Idea Grove.")
    static let noAliveIdeas = String(localized: "No Alive ideas")
    static let aliveEmptyBody = String(localized: "Completed ideas can be revived whenever you want to build on them again.")
    static let noCompletedIdeas = String(localized: "No Completed ideas yet")
    static let completedEmptyBody = String(localized: "When an idea is done for now, mark it Completed. If a Pulse is complete as-is, mark it as an Insight.")
    static let insightBody = String(localized: "This Pulse was marked as an Insight. It is complete as-is, but you can revive it if you want to build on it later.")
    static let showMore = String(localized: "Show more")
    static let showLess = String(localized: "Show less")
    static let activeFlow = String(localized: "A Flow is already running.")
    static let viewFlow = String(localized: "View Flow")
    static let loadError = String(localized: "Scyra couldn’t load Idea Grove. Try again.")
}
